name: Test download
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
      - name: start test
        run: |
          wget "https://d900.files-cdn.com/d/xuco7obuofuuxiqnhzfoeaa6icbd444hgnaakmhilw3whxhz2vbfwixdlpkq22nsjce6km5ksdx7oyi/L'Age_De_Glace_5.les_Lois_de_l'Univers.VFF.HDLight.1080p.x264-Wawacity.beer.mkv"
          sudo apt install ffmpeg
          ffmpeg -i *.mkv -c:v libx264 -c:a aac -preset fast test.mp4
      - name: release test
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test
          name: result test
          files:  test.mp4 
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
